create database commands;
use commands;
create table main (name varchar(20),age int);
select * from main;
insert into main values("arun",20);
insert into main (name) values ('ko'),('sa');
set sql_safe_updates=0;
insert into main values("aj",20),("mj",30);
create table mai (name varchar(20),age int);
insert into mai values("arun",20),('ki',25),('ko',25),('sa',40);
select * from mai;
truncate table mai;
update main,mai set main.age=mai.age where main.name=mai.name;
delete from mai where age is not null;
drop table mai;
delete from main;
update myemp as m join (select dep_id,avg(salary) as avg_salary from myemp sub group by 1)s on m.dep_id=s.dep_id set m.avg_salary = s.avg_salary;
Alter table myemp modify column p varchar(20);
use learndb;
update myemp as m join (select dep_id,avg(salary) as avg_salary from myemp sub group by 1)s on m.dep_id=s.dep_id set m.avg_salary = s.avg_salary;
update myemp as m join (select emp_id,avg(salary) over (partition by dep_id) as avg_salary from myemp)s on m.emp_id=s.emp_id set  m.avg_salary=s.avg_salary;
start transaction;
alter table myemp add column avg_salary int;
select * from myemp;
alter table main add column name int ;
rollback;